apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: notification-api
  description: "Consumes greeting events from a queue and writes notification reports"
  annotations:
    github.com/project-slug: wasp-foundry/notification-api
    backstage.io/techdocs-ref: dir:.
    backstage.io/kubernetes-id: notification-api
spec:
  type: service
  lifecycle: experimental
  system: notifier
  owner: "group:default/team-beta"
  dependsOn:
    - resource:default/development
    - resource:default/production
